export const informationDisability = {
  idIncapacidad: 0,
  radicado: 0,
  fkIdTipoIncapacidad: 0,
  fkNitEmpresa: '',
  numeroIncapacidad: 0,
  fechaInicio: '',
  fechaFin: '',
  totalDias: 0,
  ibc: 0,
  valor: 0,
  idGrupoCie: 0,
  fkIdEstadoIncapacidad: 0,
  cie: '',
  fkDocumentoPersona: 0,
  fkEntidad: '',
  primerNombre: '',
  segundoNombre: '',
  primerApellido: '',
  segundoApellido: '',
  genero: '',
  fechaNacimiento: '',
  fkIdTipoDocumento: 0,
  nombreTipoDocumento: '',
  nombreTipoIncapacidad: '',
  codigoDianostico: '',
  nit: '',
  nitEntidad: '',
  razonSocial: '',
  fkIdTipoEmpresa: 0,
  nitArl: '',
  razonSocialArl: '',
  nitAfp: '',
  razonSocialAfp: '',
  nitEps: '',
  razonSocialEps: '',
  nombreEstadoIncapacidad: '',
  fechaRegistro: '',
  files: [],
};

export const disabilityDetailDefinition = {
  disability: {
    'NIT EMPRESA': '',
    'EMPRESA EMPLEADO': '',
    'NÚMERO INCAPACIDAD': 0,
    'FECHA INICIO': '',
    'FECHA FIN': '',
    'TOTAL DÍAS': 0,
    IBC: 0,
    VALOR: 0,
    'ESTADO INCAPACIDAD': '',
    'TIPO INCAPACIDAD': '',
    'NIT ENTIDAD': '',
    ENTIDAD: '',
    'TIPO ENTIDAD': '',
    CIE: '',
    CÓDIGO: '',
    DESCRIPCIÓN: '',
    'CÓDIGO GRUPO': '',
    'FECHA REGIRSTRO': '',
  },
  employe: {
    DOCUMENTO: 0,
    'PRIMER NOMBRE': '',
    'SEGUNDO NOMBRE': '',
    'PRIMERA PELLIDO': '',
    'SEGUNDO APELLIDO': '',
    GÉNERO: '',
    'FECHA NACIMIENTO': '',
    'DOCUMENTO EMPLEADO': 0,
    DIRECCIÓN: '',
    BARRIO: '',
    CORREO: '',
    CELULAR: '',
    TELEFONO: '',
    'CIUDAD RESIDENCIA': '',
    'DEPARTAMENTO RESIDENCIA': '',
    CARGO: '',
    'TIPO DOCUMENTO': '',
  },
};
